# Generated by Django 4.2.2 on 2023-06-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вьетнам', max_length=20, verbose_name='название страны')),
            ],
            options={
                'verbose_name': 'страна производства',
                'verbose_name_plural': 'страны производства',
                'ordering': ('name',),
            },
        ),
    ]
