# Generated by Django 4.2.2 on 2023-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='IERM7.WW2', max_length=50, null=True, unique=True)),
                ('ean', models.IntegerField(help_text='4548736081680', unique=True, verbose_name='штрихкод')),
                ('name', models.CharField(help_text='IER-M7', max_length=100, verbose_name='наименование')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=7, verbose_name='старая цена')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='цена')),
                ('red_price', models.BooleanField(verbose_name='красный ценник')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='последнее обновление')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('-updated_at', 'ean', 'sku'),
            },
        ),
    ]
