# Generated by Django 4.2.2 on 2023-06-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0004_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='priceapp.category', verbose_name='категория'),
            preserve_default=False,
        ),
    ]
