# Generated by Django 4.2.2 on 2023-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название ценника')),
                ('width', models.IntegerField(verbose_name='ширина')),
                ('height', models.IntegerField(verbose_name='высота')),
                ('size', models.CharField(choices=[('big', 'big'), ('small', 'small')], default='big', max_length=5, verbose_name='размер ценника')),
                ('is_discount', models.BooleanField(default=False, verbose_name='двойной ценник')),
            ],
            options={
                'verbose_name': 'ценник',
                'verbose_name_plural': 'ценники',
                'ordering': ('is_discount', 'name'),
            },
        ),
    ]
