# Generated by Django 4.2.2 on 2023-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0006_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True, verbose_name='дата печати')),
                ('discount_type', models.CharField(blank=True, default='Акция !!!', max_length=40, verbose_name='причина скидки')),
                ('product', models.CharField(help_text='WF-1000XM4', max_length=100, verbose_name='наименование')),
                ('price', models.DecimalField(decimal_places=0, help_text='19990', max_digits=10, verbose_name='цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, help_text='25990', max_digits=10, verbose_name='старая цена')),
                ('red_price', models.BooleanField(default=False, verbose_name='красная цена')),
            ],
            options={
                'verbose_name': 'ценник для печати',
                'verbose_name_plural': 'ценники для печати',
                'ordering': ('printed_at',),
            },
        ),
    ]
