# Generated by Django 4.2.2 on 2023-06-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0009_printsheet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsheet',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='priceapp.tag', verbose_name='ценник'),
        ),
    ]
