# Generated by Django 4.2.2 on 2023-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0010_printsheet_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='наименование')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='цена')),
                ('old_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='старая цена')),
                ('red_price', models.BooleanField(default=False, verbose_name='красная цена')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'обновляемый товар',
                'verbose_name_plural': 'список обновления',
                'ordering': ('update_at',),
            },
        ),
    ]
