# Generated by Django 4.2.2 on 2023-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0016_alter_missingproduct_sku_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingproduct',
            name='ean',
            field=models.CharField(blank=True, help_text='4548736081680', max_length=13, null=True, unique=True, verbose_name='штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(help_text='4548736081680', max_length=13, unique=True, verbose_name='штрихкод'),
        ),
    ]
