# Generated by Django 4.2.2 on 2023-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0018_rename_product_printsheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsheet',
            name='category',
            field=models.CharField(help_text='BT наушники', max_length=40, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='printsheet',
            name='country',
            field=models.CharField(help_text='Малайзия', max_length=30, verbose_name='страна'),
        ),
    ]
