# Generated by Django 4.2.2 on 2023-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0019_alter_printsheet_category_alter_printsheet_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(db_index=True, help_text='4548736081680', max_length=13, unique=True, verbose_name='штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, help_text='IER-M7', max_length=100, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='IERM7.WW2', max_length=50, null=True),
        ),
    ]
